# Generated by Django 3.2.10 on 2022-02-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20220201_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replaycomment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replaies', to='comment.comment'),
        ),
    ]
